### ISSUE TITLE
Work with Firefox's Reader Mode

### ISSUE THREAD

**Issue by Caspy7** [ntv1000/reddit-submission-finder#4]
I use your addon frequently and use Reader mode just as frequently, but once I've entered reader mode the addon does not function properly.

What the addon sees is _about:reader?url=_ appended to the front of the URL.
It should detect this URL (or detect if it's in reader mode) and strip this part out before queries or submissions to reddit.

**Comment by ntv1000** [comment]
Thank you for the report, I will do this as soon as I find the time.
