### ISSUE TITLE
Suggestion for improvement with YouTube URLs

### ISSUE THREAD

**Issue by CaptainBlagbird** [ntv1000/reddit-submission-finder#5]
Very useful add-on, but here is a suggestions for improvement with YouTube URLs:

**Use the youtube ID and domain seperately as search term**
E.g. see the difference between these searches:
- [ID and domain seperately](https://www.reddit.com/search?q=site%3Ayoutube.com+OR+site%3Ayoutu.be+url%3A4XGHu28Y1FQ&restrict_sr=&sort=relevance&t=all)
- [Short URL](https://www.reddit.com/search?q=url%3Ayoutu.be%2F4XGHu28Y1FQ&restrict_sr=&sort=relevance&t=all)
- [Default URL](https://www.reddit.com/search?q=url%3Ahttps%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D4XGHu28Y1FQ&restrict_sr=&sort=relevance&t=all)

**Comment by ntv1000** [comment]
Hello, as far as I understand this is already happening exactly as you mean it. See the relevant line: [index.js#L201](https://github.com/ntv1000/reddit-submission-finder/blob/ee3a50eaf7649474a9058d09a59e0249496a78b8/index.js#L201)

The search term it produces for the example you provided would be: 
`(url:4XGHu28Y1FQ) (site:youtube.com OR site:youtu.be)`
I also tried it directly in the addon and it displays all of the 3 reddit submissions.

I am closing this, but if I am misunderstanding anything here please point it out to me.
